### ISSUE TITLE
Deprecation error in Developer Tools

### ISSUE THREAD

**Issue by mfromin** [drewhamlett/brackets-beautify#154]
I see this several times in the dev tools in Brackets.  Not sure if you were aware or not...

```
Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:479:36)
    at n (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:405)
    at file:///Users/mfromin/Library/Application%20Support/Brackets/extensions/user/brackets-beautify/main.js:317:9
    at _callHandler (/utils/AppInit.js:93:13)
    at Object._dispatchReady (/utils/AppInit.js:113:13)
    at Object.eval (/brackets.js:291:33)
    at j (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:26911)
    at Object.k.add [as done] (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:27220)
    at Object.d.always (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:559:28096)
```

**Comment by drewhamlett** [comment]
Hi I have fixed the deprecation notices in this extension.  It seems it still shows up, but I think it's for other extensions, or internal code.  Thanks!
