### ISSUE TITLE
Deprecated

### ISSUE THREAD

**Issue by iNovozhilov** [drewhamlett/brackets-beautify#155]
sprint 3 build 1.3.0-16022 (release cd0a6aae5) 

Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:479:36)
    at n (file:///C:/Program%20Files/Brackets/www/thirdparty/thirdparty.min.js:559:405)
    at toggle (file:///C:/Users/admin/AppData/Roaming/Brackets/extensions/user/brackets-beautify/main.js:285:9)
    at Object.<anonymous> (file:///C:/Users/admin/AppData/Roaming/Brackets/extensions/user/brackets-beautify/main.js:309:5)
/LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:87 NodeSocketTransport - start
/utils/DeprecationWarning.js:90 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:479:36)
    at n (file:///C:/Program%20Files/Brackets/www/thirdparty/thirdparty.min.js:559:405)
    at file:///C:/Users/admin/AppData/Roaming/Brackets/extensions/user/brackets-beautify/main.js:317:9
    at _callHandler (/utils/AppInit.js:93:13)
    at Object._dispatchReady (/utils/AppInit.js:113:13)
    at Object.eval (/brackets.js:291:33)
    at j (file:///C:/Program%20Files/Brackets/www/thirdparty/thirdparty.min.js:559:26911)
    at Object.k.add [as done] (file:///C:/Program%20Files/Brackets/www/thirdparty/thirdparty.min.js:559:27220)
    at Object.d.always (file:///C:/Program%20Files/Brackets/www/thirdparty/thirdparty.min.js:559:28096)
/utils/DeprecationWarning.js:90 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:479:36)
    at n (file:///C:/Program%20Files/Brackets/www/thirdparty/thirdparty.min.js:559:405)
    at file:///C:/Users/admin/AppData/Roaming/Brackets/extensions/user/brackets-beautify/main.js:323:9
    at _callHandler (/utils/AppInit.js:93:13)
    at Object._dispatchReady (/utils/AppInit.js:113:13)
    at Object.eval (/brackets.js:291:33)
    at j (file:///C:/Program%20Files/Brackets/www/thirdparty/thirdparty.min.js:559:26911)
    at Object.k.add [as done] (file:///C:/Program%20Files/Brackets/www/thirdparty/thirdparty.min.js:559:27220)
    at Object.d.always (file:///C:/Program%20Files/Brackets/www/thirdparty/thirdparty.min.js:559:28096)

**Comment by cgfrost** [comment]
Still showing up in Brackets 1.3

**Comment by drewhamlett** [comment]
I have fixed the deprecation notices for this extension.  It will still show up but I believe it's internal code.  Thanks!
